stages:
  - build
  - test
  - docker-push

variables:
  IMAGE: '$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG'
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  image: amazoncorretto:17-alpine
  only:
    - main
  cache:
    - key: $CI_COMMIT_REF_SLUG
      paths:
        - .gradle/
    - key: $CI_PIPELINE_ID
      policy: push
      paths:
        - app/build/
  script:
    - ./gradlew jibBuildTar --image=$IMAGE
    # build standalone jar and save as job artifact
#    - ./gradlew build

run-tests:
  stage: test
  image: amazoncorretto:17-alpine
  services:
    - redis:alpine
  variables:
    "jedis.redis.path": "redis://redis:6379"
  only:
    variables:
      # run for protected branches only
      - $CI_COMMIT_REF_PROTECTED == 'true'
  cache:
    - key: $CI_COMMIT_REF_SLUG
      policy: pull
      paths:
        - .gradle/
    - key: $CI_PIPELINE_ID
      policy: pull
      paths:
        - build/
  script:
    - ./gradlew jacocoTestReport
    - awk -F, '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' app/build/reports/jacoco/test/jacocoTestReport.csv
  coverage: '/([\d,.]+) \% covered/'

docker-push:
  stage: docker-push
  image: docker:stable
  only:
    - main
  cache:
    key: $CI_PIPELINE_ID
    policy: pull
    paths:
      - app/build/
  services:
    - docker:stable-dind
  variables:
    GIT_STRATEGY: none
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker load --input app/build/jib-image.tar
    - docker push $IMAGE
