services:

  ydb_dev:
    container_name: bookkeeper-ydb-dev
    image: ydbplatform/local-ydb:latest
    restart: unless-stopped
    hostname: localhost
    environment:
      - MON_PORT=8765
      - GRPC_PORT=2136
    ports:
      - '2136:2136'
      - '8765:8765'

  redis_dev:
    container_name: bookkeeper-redis-dev
    image: redis:alpine
    restart: unless-stopped
    ports:
      - '6390:6379'
