version: '3'
services:

  postgres_dev:
    container_name: bookkeeper-postgres-dev
    image: 'postgres:15-alpine'
    restart: unless-stopped
    environment:
      - POSTGRES_DATABASE=bookkeeper
      - POSTGRES_USER=bookkeeper
      - POSTGRES_PASSWORD=bookkeeper
    volumes:
      - 'postgres_dev:/var/lib/postgresql/data'
    ports:
      - '5434:5432'

  redis_dev:
    container_name: bookkeeper-redis-dev
    image: redis:alpine
    restart: unless-stopped
    ports:
      - '6390:6379'

volumes:
  postgres_dev:
    name: bookkeeper-postgres-dev

networks:
  default:
    name: 'bookkeeper-dev-network'
