services:

  app:
    container_name: bookkeeper-app
    image: "${DOCKER_IMAGE}"
    links:
      - redis
    restart: unless-stopped
    environment:
      - NOTIFY_TELEGRAM_USER_ID=${NOTIFY_TELEGRAM_USER_ID}
      - BOT_TOKEN=${BOT_TOKEN}
      - JEDIS_REDIS_PATH=redis://redis:6379
      - JAKARTA_PERSISTENCE_JDBC_URL=${JDBC_URL}
    volumes:
      - './${YDB_SA_KEY_PATH}:/sa_key.json'

  redis:
    container_name: bookkeeper-redis
    image: redis:alpine
    restart: unless-stopped
